// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	MacdStrategies string
	MfiStrategies  string
	RsiStrategies  string
	StrategyEvents string
	Users          string
}{
	MacdStrategies: "macd_strategies",
	MfiStrategies:  "mfi_strategies",
	RsiStrategies:  "rsi_strategies",
	StrategyEvents: "strategy_events",
	Users:          "users",
}
