// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testMfiStrategies(t *testing.T) {
	t.Parallel()

	query := MfiStrategies()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testMfiStrategiesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MfiStrategy{}
	if err = randomize.Struct(seed, o, mfiStrategyDBTypes, true, mfiStrategyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MfiStrategy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := MfiStrategies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testMfiStrategiesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MfiStrategy{}
	if err = randomize.Struct(seed, o, mfiStrategyDBTypes, true, mfiStrategyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MfiStrategy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := MfiStrategies().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := MfiStrategies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testMfiStrategiesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MfiStrategy{}
	if err = randomize.Struct(seed, o, mfiStrategyDBTypes, true, mfiStrategyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MfiStrategy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := MfiStrategySlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := MfiStrategies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testMfiStrategiesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MfiStrategy{}
	if err = randomize.Struct(seed, o, mfiStrategyDBTypes, true, mfiStrategyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MfiStrategy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := MfiStrategyExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if MfiStrategy exists: %s", err)
	}
	if !e {
		t.Errorf("Expected MfiStrategyExists to return true, but got false.")
	}
}

func testMfiStrategiesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MfiStrategy{}
	if err = randomize.Struct(seed, o, mfiStrategyDBTypes, true, mfiStrategyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MfiStrategy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	mfiStrategyFound, err := FindMfiStrategy(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if mfiStrategyFound == nil {
		t.Error("want a record, got nil")
	}
}

func testMfiStrategiesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MfiStrategy{}
	if err = randomize.Struct(seed, o, mfiStrategyDBTypes, true, mfiStrategyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MfiStrategy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = MfiStrategies().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testMfiStrategiesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MfiStrategy{}
	if err = randomize.Struct(seed, o, mfiStrategyDBTypes, true, mfiStrategyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MfiStrategy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := MfiStrategies().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testMfiStrategiesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	mfiStrategyOne := &MfiStrategy{}
	mfiStrategyTwo := &MfiStrategy{}
	if err = randomize.Struct(seed, mfiStrategyOne, mfiStrategyDBTypes, false, mfiStrategyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MfiStrategy struct: %s", err)
	}
	if err = randomize.Struct(seed, mfiStrategyTwo, mfiStrategyDBTypes, false, mfiStrategyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MfiStrategy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = mfiStrategyOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = mfiStrategyTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := MfiStrategies().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testMfiStrategiesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	mfiStrategyOne := &MfiStrategy{}
	mfiStrategyTwo := &MfiStrategy{}
	if err = randomize.Struct(seed, mfiStrategyOne, mfiStrategyDBTypes, false, mfiStrategyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MfiStrategy struct: %s", err)
	}
	if err = randomize.Struct(seed, mfiStrategyTwo, mfiStrategyDBTypes, false, mfiStrategyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MfiStrategy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = mfiStrategyOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = mfiStrategyTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := MfiStrategies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func mfiStrategyBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *MfiStrategy) error {
	*o = MfiStrategy{}
	return nil
}

func mfiStrategyAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *MfiStrategy) error {
	*o = MfiStrategy{}
	return nil
}

func mfiStrategyAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *MfiStrategy) error {
	*o = MfiStrategy{}
	return nil
}

func mfiStrategyBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *MfiStrategy) error {
	*o = MfiStrategy{}
	return nil
}

func mfiStrategyAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *MfiStrategy) error {
	*o = MfiStrategy{}
	return nil
}

func mfiStrategyBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *MfiStrategy) error {
	*o = MfiStrategy{}
	return nil
}

func mfiStrategyAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *MfiStrategy) error {
	*o = MfiStrategy{}
	return nil
}

func mfiStrategyBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *MfiStrategy) error {
	*o = MfiStrategy{}
	return nil
}

func mfiStrategyAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *MfiStrategy) error {
	*o = MfiStrategy{}
	return nil
}

func testMfiStrategiesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &MfiStrategy{}
	o := &MfiStrategy{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, mfiStrategyDBTypes, false); err != nil {
		t.Errorf("Unable to randomize MfiStrategy object: %s", err)
	}

	AddMfiStrategyHook(boil.BeforeInsertHook, mfiStrategyBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	mfiStrategyBeforeInsertHooks = []MfiStrategyHook{}

	AddMfiStrategyHook(boil.AfterInsertHook, mfiStrategyAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	mfiStrategyAfterInsertHooks = []MfiStrategyHook{}

	AddMfiStrategyHook(boil.AfterSelectHook, mfiStrategyAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	mfiStrategyAfterSelectHooks = []MfiStrategyHook{}

	AddMfiStrategyHook(boil.BeforeUpdateHook, mfiStrategyBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	mfiStrategyBeforeUpdateHooks = []MfiStrategyHook{}

	AddMfiStrategyHook(boil.AfterUpdateHook, mfiStrategyAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	mfiStrategyAfterUpdateHooks = []MfiStrategyHook{}

	AddMfiStrategyHook(boil.BeforeDeleteHook, mfiStrategyBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	mfiStrategyBeforeDeleteHooks = []MfiStrategyHook{}

	AddMfiStrategyHook(boil.AfterDeleteHook, mfiStrategyAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	mfiStrategyAfterDeleteHooks = []MfiStrategyHook{}

	AddMfiStrategyHook(boil.BeforeUpsertHook, mfiStrategyBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	mfiStrategyBeforeUpsertHooks = []MfiStrategyHook{}

	AddMfiStrategyHook(boil.AfterUpsertHook, mfiStrategyAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	mfiStrategyAfterUpsertHooks = []MfiStrategyHook{}
}

func testMfiStrategiesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MfiStrategy{}
	if err = randomize.Struct(seed, o, mfiStrategyDBTypes, true, mfiStrategyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MfiStrategy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := MfiStrategies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testMfiStrategiesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MfiStrategy{}
	if err = randomize.Struct(seed, o, mfiStrategyDBTypes, true); err != nil {
		t.Errorf("Unable to randomize MfiStrategy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(mfiStrategyColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := MfiStrategies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testMfiStrategyToOneUserUsingUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local MfiStrategy
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, mfiStrategyDBTypes, false, mfiStrategyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MfiStrategy struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.UserID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := MfiStrategySlice{&local}
	if err = local.L.LoadUser(ctx, tx, false, (*[]*MfiStrategy)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User = nil
	if err = local.L.LoadUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testMfiStrategyToOneSetOpUserUsingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a MfiStrategy
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, mfiStrategyDBTypes, false, strmangle.SetComplement(mfiStrategyPrimaryKeyColumns, mfiStrategyColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.MfiStrategies[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserID))
		reflect.Indirect(reflect.ValueOf(&a.UserID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID, x.ID)
		}
	}
}

func testMfiStrategiesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MfiStrategy{}
	if err = randomize.Struct(seed, o, mfiStrategyDBTypes, true, mfiStrategyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MfiStrategy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testMfiStrategiesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MfiStrategy{}
	if err = randomize.Struct(seed, o, mfiStrategyDBTypes, true, mfiStrategyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MfiStrategy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := MfiStrategySlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testMfiStrategiesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MfiStrategy{}
	if err = randomize.Struct(seed, o, mfiStrategyDBTypes, true, mfiStrategyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MfiStrategy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := MfiStrategies().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	mfiStrategyDBTypes = map[string]string{`ID`: `character varying`, `UserID`: `character varying`, `Name`: `character varying`, `Instrument`: `character varying`, `Granularity`: `character varying`, `OverboughtLevel`: `integer`, `OversoldLevel`: `integer`, `Status`: `character varying`, `CreatedOn`: `timestamp without time zone`, `LastEditedOn`: `timestamp without time zone`, `DeletedOn`: `timestamp without time zone`}
	_                  = bytes.MinRead
)

func testMfiStrategiesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(mfiStrategyPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(mfiStrategyAllColumns) == len(mfiStrategyPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &MfiStrategy{}
	if err = randomize.Struct(seed, o, mfiStrategyDBTypes, true, mfiStrategyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MfiStrategy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := MfiStrategies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, mfiStrategyDBTypes, true, mfiStrategyPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize MfiStrategy struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testMfiStrategiesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(mfiStrategyAllColumns) == len(mfiStrategyPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &MfiStrategy{}
	if err = randomize.Struct(seed, o, mfiStrategyDBTypes, true, mfiStrategyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MfiStrategy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := MfiStrategies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, mfiStrategyDBTypes, true, mfiStrategyPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize MfiStrategy struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(mfiStrategyAllColumns, mfiStrategyPrimaryKeyColumns) {
		fields = mfiStrategyAllColumns
	} else {
		fields = strmangle.SetComplement(
			mfiStrategyAllColumns,
			mfiStrategyPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := MfiStrategySlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testMfiStrategiesUpsert(t *testing.T) {
	t.Parallel()

	if len(mfiStrategyAllColumns) == len(mfiStrategyPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := MfiStrategy{}
	if err = randomize.Struct(seed, &o, mfiStrategyDBTypes, true); err != nil {
		t.Errorf("Unable to randomize MfiStrategy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert MfiStrategy: %s", err)
	}

	count, err := MfiStrategies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, mfiStrategyDBTypes, false, mfiStrategyPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize MfiStrategy struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert MfiStrategy: %s", err)
	}

	count, err = MfiStrategies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
