// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testRsiStrategies(t *testing.T) {
	t.Parallel()

	query := RsiStrategies()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testRsiStrategiesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RsiStrategy{}
	if err = randomize.Struct(seed, o, rsiStrategyDBTypes, true, rsiStrategyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RsiStrategy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := RsiStrategies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRsiStrategiesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RsiStrategy{}
	if err = randomize.Struct(seed, o, rsiStrategyDBTypes, true, rsiStrategyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RsiStrategy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := RsiStrategies().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := RsiStrategies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRsiStrategiesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RsiStrategy{}
	if err = randomize.Struct(seed, o, rsiStrategyDBTypes, true, rsiStrategyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RsiStrategy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := RsiStrategySlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := RsiStrategies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRsiStrategiesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RsiStrategy{}
	if err = randomize.Struct(seed, o, rsiStrategyDBTypes, true, rsiStrategyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RsiStrategy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := RsiStrategyExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if RsiStrategy exists: %s", err)
	}
	if !e {
		t.Errorf("Expected RsiStrategyExists to return true, but got false.")
	}
}

func testRsiStrategiesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RsiStrategy{}
	if err = randomize.Struct(seed, o, rsiStrategyDBTypes, true, rsiStrategyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RsiStrategy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	rsiStrategyFound, err := FindRsiStrategy(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if rsiStrategyFound == nil {
		t.Error("want a record, got nil")
	}
}

func testRsiStrategiesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RsiStrategy{}
	if err = randomize.Struct(seed, o, rsiStrategyDBTypes, true, rsiStrategyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RsiStrategy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = RsiStrategies().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testRsiStrategiesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RsiStrategy{}
	if err = randomize.Struct(seed, o, rsiStrategyDBTypes, true, rsiStrategyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RsiStrategy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := RsiStrategies().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testRsiStrategiesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	rsiStrategyOne := &RsiStrategy{}
	rsiStrategyTwo := &RsiStrategy{}
	if err = randomize.Struct(seed, rsiStrategyOne, rsiStrategyDBTypes, false, rsiStrategyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RsiStrategy struct: %s", err)
	}
	if err = randomize.Struct(seed, rsiStrategyTwo, rsiStrategyDBTypes, false, rsiStrategyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RsiStrategy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = rsiStrategyOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = rsiStrategyTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := RsiStrategies().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testRsiStrategiesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	rsiStrategyOne := &RsiStrategy{}
	rsiStrategyTwo := &RsiStrategy{}
	if err = randomize.Struct(seed, rsiStrategyOne, rsiStrategyDBTypes, false, rsiStrategyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RsiStrategy struct: %s", err)
	}
	if err = randomize.Struct(seed, rsiStrategyTwo, rsiStrategyDBTypes, false, rsiStrategyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RsiStrategy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = rsiStrategyOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = rsiStrategyTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := RsiStrategies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func rsiStrategyBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *RsiStrategy) error {
	*o = RsiStrategy{}
	return nil
}

func rsiStrategyAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *RsiStrategy) error {
	*o = RsiStrategy{}
	return nil
}

func rsiStrategyAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *RsiStrategy) error {
	*o = RsiStrategy{}
	return nil
}

func rsiStrategyBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *RsiStrategy) error {
	*o = RsiStrategy{}
	return nil
}

func rsiStrategyAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *RsiStrategy) error {
	*o = RsiStrategy{}
	return nil
}

func rsiStrategyBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *RsiStrategy) error {
	*o = RsiStrategy{}
	return nil
}

func rsiStrategyAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *RsiStrategy) error {
	*o = RsiStrategy{}
	return nil
}

func rsiStrategyBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *RsiStrategy) error {
	*o = RsiStrategy{}
	return nil
}

func rsiStrategyAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *RsiStrategy) error {
	*o = RsiStrategy{}
	return nil
}

func testRsiStrategiesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &RsiStrategy{}
	o := &RsiStrategy{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, rsiStrategyDBTypes, false); err != nil {
		t.Errorf("Unable to randomize RsiStrategy object: %s", err)
	}

	AddRsiStrategyHook(boil.BeforeInsertHook, rsiStrategyBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	rsiStrategyBeforeInsertHooks = []RsiStrategyHook{}

	AddRsiStrategyHook(boil.AfterInsertHook, rsiStrategyAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	rsiStrategyAfterInsertHooks = []RsiStrategyHook{}

	AddRsiStrategyHook(boil.AfterSelectHook, rsiStrategyAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	rsiStrategyAfterSelectHooks = []RsiStrategyHook{}

	AddRsiStrategyHook(boil.BeforeUpdateHook, rsiStrategyBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	rsiStrategyBeforeUpdateHooks = []RsiStrategyHook{}

	AddRsiStrategyHook(boil.AfterUpdateHook, rsiStrategyAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	rsiStrategyAfterUpdateHooks = []RsiStrategyHook{}

	AddRsiStrategyHook(boil.BeforeDeleteHook, rsiStrategyBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	rsiStrategyBeforeDeleteHooks = []RsiStrategyHook{}

	AddRsiStrategyHook(boil.AfterDeleteHook, rsiStrategyAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	rsiStrategyAfterDeleteHooks = []RsiStrategyHook{}

	AddRsiStrategyHook(boil.BeforeUpsertHook, rsiStrategyBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	rsiStrategyBeforeUpsertHooks = []RsiStrategyHook{}

	AddRsiStrategyHook(boil.AfterUpsertHook, rsiStrategyAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	rsiStrategyAfterUpsertHooks = []RsiStrategyHook{}
}

func testRsiStrategiesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RsiStrategy{}
	if err = randomize.Struct(seed, o, rsiStrategyDBTypes, true, rsiStrategyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RsiStrategy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := RsiStrategies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testRsiStrategiesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RsiStrategy{}
	if err = randomize.Struct(seed, o, rsiStrategyDBTypes, true); err != nil {
		t.Errorf("Unable to randomize RsiStrategy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(rsiStrategyColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := RsiStrategies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testRsiStrategyToOneUserUsingUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local RsiStrategy
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, rsiStrategyDBTypes, false, rsiStrategyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RsiStrategy struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.UserID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := RsiStrategySlice{&local}
	if err = local.L.LoadUser(ctx, tx, false, (*[]*RsiStrategy)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User = nil
	if err = local.L.LoadUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testRsiStrategyToOneSetOpUserUsingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a RsiStrategy
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, rsiStrategyDBTypes, false, strmangle.SetComplement(rsiStrategyPrimaryKeyColumns, rsiStrategyColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.RsiStrategies[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserID))
		reflect.Indirect(reflect.ValueOf(&a.UserID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID, x.ID)
		}
	}
}

func testRsiStrategiesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RsiStrategy{}
	if err = randomize.Struct(seed, o, rsiStrategyDBTypes, true, rsiStrategyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RsiStrategy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testRsiStrategiesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RsiStrategy{}
	if err = randomize.Struct(seed, o, rsiStrategyDBTypes, true, rsiStrategyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RsiStrategy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := RsiStrategySlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testRsiStrategiesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RsiStrategy{}
	if err = randomize.Struct(seed, o, rsiStrategyDBTypes, true, rsiStrategyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RsiStrategy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := RsiStrategies().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	rsiStrategyDBTypes = map[string]string{`ID`: `character varying`, `UserID`: `character varying`, `Name`: `character varying`, `Instrument`: `character varying`, `Granularity`: `character varying`, `OverboughtLevel`: `integer`, `OversoldLevel`: `integer`, `Status`: `character varying`, `CreatedOn`: `timestamp without time zone`, `LastEditedOn`: `timestamp without time zone`, `DeletedOn`: `timestamp without time zone`}
	_                  = bytes.MinRead
)

func testRsiStrategiesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(rsiStrategyPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(rsiStrategyAllColumns) == len(rsiStrategyPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &RsiStrategy{}
	if err = randomize.Struct(seed, o, rsiStrategyDBTypes, true, rsiStrategyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RsiStrategy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := RsiStrategies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, rsiStrategyDBTypes, true, rsiStrategyPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize RsiStrategy struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testRsiStrategiesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(rsiStrategyAllColumns) == len(rsiStrategyPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &RsiStrategy{}
	if err = randomize.Struct(seed, o, rsiStrategyDBTypes, true, rsiStrategyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RsiStrategy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := RsiStrategies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, rsiStrategyDBTypes, true, rsiStrategyPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize RsiStrategy struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(rsiStrategyAllColumns, rsiStrategyPrimaryKeyColumns) {
		fields = rsiStrategyAllColumns
	} else {
		fields = strmangle.SetComplement(
			rsiStrategyAllColumns,
			rsiStrategyPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := RsiStrategySlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testRsiStrategiesUpsert(t *testing.T) {
	t.Parallel()

	if len(rsiStrategyAllColumns) == len(rsiStrategyPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := RsiStrategy{}
	if err = randomize.Struct(seed, &o, rsiStrategyDBTypes, true); err != nil {
		t.Errorf("Unable to randomize RsiStrategy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert RsiStrategy: %s", err)
	}

	count, err := RsiStrategies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, rsiStrategyDBTypes, false, rsiStrategyPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize RsiStrategy struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert RsiStrategy: %s", err)
	}

	count, err = RsiStrategies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
